name: weather-pipeline

default_environment: default

environments:
  default:
    connections:
      postgres:
        - name: "postgres_default"
          host: "${BRUIN_PG_HOST}"
          port: 5432
          database: "${BRUIN_PG_DB}"
          username: "${BRUIN_PG_USER}"
          password: "${BRUIN_PG_PASSWORD}"
          ssl_mode: "disable"
